"""create initial tables

Revision ID: d28d82c7a598
Revises: 78608833fbb0
Create Date: 2025-10-24 13:27:27.695797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'd28d82c7a598'
down_revision: Union[str, Sequence[str], None] = '78608833fbb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mixes_created_at'), table_name='mixes')
    op.drop_index(op.f('ix_mixes_id'), table_name='mixes')
    op.drop_index(op.f('ix_mixes_status'), table_name='mixes')
    op.drop_index(op.f('ix_mixes_title'), table_name='mixes')
    op.drop_table('mixes')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_activity_mix_id'), table_name='user_activity')
    op.drop_index(op.f('ix_user_activity_user_id'), table_name='user_activity')
    op.drop_index(op.f('ix_user_mix_time'), table_name='user_activity')
    op.drop_table('user_activity')
    op.drop_index(op.f('ix_mix_contents_mix_id'), table_name='mix_contents')
    op.drop_table('mix_contents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mix_contents',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('mix_id', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('image_url', sa.VARCHAR(), nullable=True),
    sa.Column('content_id', sa.VARCHAR(), nullable=True),
    sa.Column('tags', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['mix_id'], ['mixes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mix_contents_mix_id'), 'mix_contents', ['mix_id'], unique=False)
    op.create_table('user_activity',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('mix_id', sa.VARCHAR(), nullable=False),
    sa.Column('event_type', sa.VARCHAR(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['mix_id'], ['mixes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_mix_time'), 'user_activity', ['user_id', 'mix_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_user_activity_user_id'), 'user_activity', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_activity_mix_id'), 'user_activity', ['mix_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('metadata', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mixes',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('filename', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mixes_title'), 'mixes', ['title'], unique=False)
    op.create_index(op.f('ix_mixes_status'), 'mixes', ['status'], unique=False)
    op.create_index(op.f('ix_mixes_id'), 'mixes', ['id'], unique=False)
    op.create_index(op.f('ix_mixes_created_at'), 'mixes', ['created_at'], unique=False)
    # ### end Alembic commands ###
